### PR TITLE
Add .NET Core Version of FluentFTP

### PR DESCRIPTION
**Pull request by hamu01**
Add .NET Core Version of FluentFTP,  there is a bug when upload file, sometimes it only upload partial document, I don't know why.

### CODE REVIEW

**Comment by hgupta9** [comment]
Good job! I'll check out if the normal version is compiling fine and then merge it. Thanks for the work. However in the future I think its better we do this using compiler directives so we can maintain a single source code rather than 2 versions. I will try to merge it when I get time.

**Comment by hamu01** [comment]
@hgupta9 Yes, I agree with you, I create a new version mainly because I don't want change too much. Expect a new version in nuget.

**Comment by hgupta9** [comment]
New version in nuget? Are you publishing directly now??

**Comment by hamu01** [comment]
I expect you publish a new version in nuget.
I don't publish any version to nuget, of course.

**Comment by hgupta9** [comment]
Are you working on this yet?

**Comment by hamu01** [comment]
No, the code in this feature still have problem

**Comment by hgupta9** [comment]
Done it myself. Thanks for the idea though.

**Pull request closed without merging**
