### PR TITLE
Adds Support for Task-based Asychronous Programming Pattern

### PR DESCRIPTION
**Pull request by jblacker**
This pull request contains parts 1 - 3 that I mentioned in my posted issue #76.  I have tested the functionality by uploading 1GB worth of files using both the `UploadFileAsync()` & `UploadFilesAsync()` methods.  Downloaded approx 500MB in test data using the `DownloadFileAsync()` method.   Performed file deletions and directory creations.  I do not have access to an FTP server that supports hashing, so that's untested.

Additionally, I updated the documentation throughout the FluentFTP project.

You'll need to update the nuspec and any scripts associated with nuget to property target .NET 2.0, .NET4.0, .NET4.5 - .NET4.6.1, and .NET CORE.  I added the Build Configurations, but I didn't touch any of the Nuget stuff.  I did not touch the versioning so nothing's been incremented.

### CODE REVIEW

**Comment by hgupta9** [comment]
Fantastic work, Jordan. Thanks a lot for your contributions. Much appreciated :)

**Comment by hgupta9** [comment]
I added your name into the credits :)

**Comment by hgupta9** [comment]
Can you add your test methods into `Tests.cs` and submit that too?

**Comment by hgupta9** [comment]
Do you think its a good idea to disable the Begin/End syntax for the .NET 4.5 & .NET core build with conditional compiling? Is there really any reason that the older syntax would be useful for newer projects?

**Comment by jblacker** [comment]
@hgupta9 I tested it by adding it to an application I previously wrote using this library and modifying it to make it async.  However, if you'd like I can write some tests.

Regarding disabling the Begin/End syntax:  I wouldn't disable it yet, especially with conditional compiling for two reasons.
1)  I'm currently just wrapping those Begin & End methods so they are still required.
2)  I don't think we should issue a breaking change that abruptly. 

I'd recommend that we depreciate those methods and start re-writing the async methods to be "async all the way down" (and adding cancellation support).  This will require more work than using the wrapper methods since we'll need to write some new internal methods to issue commands on the socket/streams asynchronously, but still make sure everything is thread safe and ordered operations are still properly ordered.  It should improve pipelining & general performance though if we do get these written.  

In new projects I cannot really think of _why_ the older syntax would be used, but I'd be curious if anyone else in the community has a reason to use them.

**Comment by hgupta9** [comment]
Good points. Oh and I didn't mean full blown tests. Just take like one or two methods (any method in Tests.cs) and create a copy of it with your async syntax. I can then run those "tests" on my PC to check roughly if everything looks okay.

**Comment by jblacker** [comment]
@hgupta9  Ah, no problem.  I can do that.  I'll get it done a bit later today.

**Comment by jblacker** [comment]
Doh, looks like I'm not going to get this done today.  I'll most likely have it by tomorrow though.

**Comment by jblacker** [comment]
Submitted tests as pull request #80

**Comment by hgupta9** [comment]
Thank you.

**Pull request merged**
