### PR TITLE
New - Support proxy HTTP 1.1/ User@Host

### PR DESCRIPTION
**Pull request by L3Z4**
For #7 
HTTP1.1 proxy with or without authentication,
User@Host, with or without authentication.

Futur proxy implementation will benefit from FtpClientProxy abstract class.

Usage : 
using (FtpClient cl = new FtpClientHttp11Proxy(new Proxy { Host = "127.0.0.1", Port = 3128, }))
...

### CODE REVIEW

**Comment by springcomp** [comment]
That would be really useful.
+1

**Comment by hgupta9** [comment]
When you say HTTP1.1 Proxy, Is this for connecting to a FTP through an HTTP proxy? I have never heard of FTP proxy? And what is user@host? Never heard of that either.

**Comment by L3Z4** [comment]
The FTP client you wrote is instantiated in a system inside a network. The outgoing communication can be going through a Proxy. FTP client must adapt its way to connect in this particular case.

For my tests, I used Squid proxy http://www.squid-cache.org/, this particular tutorial : https://docs.diladele.com/tutorials/installing_squid_windows/index.html

I hope it help ! Let me know if I could do anything.

**Comment by hgupta9** [comment]
@L3Z4 - I'm going to test this today, but you could help by testing the new code as well. Since you have a genuine need for a proxy, you will provide valuable feedback. Why are there 2 classes for the Proxy? I think it would be better OOP design if there was just one FtpClientProxy class, or even better if we could merge functionality into the main FtpClient class. Which would you prefer?

**Comment by L3Z4** [comment]
The option A is not acceptable : composition can be numerous. I implemented only two kind of proxy, I don't know how many exists. Idem for option B.

The option C is the closest of the implementation a pushed. I'm convinced that having a class dedicated for a proxy implementation is a good choice (S of SOLID). It is also an extension point of your library. 

I agree to add a factory method in the FtpClient class to construct a "proxified" client.
How do I update the pull request ? Should I update my branch and re-do it ? It is my first one to be honest.

**Comment by hgupta9** [comment]
Just add more commits. Github will update the PR to use your latest commit in your trunk.

I agree. Please add a `ConnectionType` or similar property, and go with Option C. Do you mean a static factory method or a dynamic one?

**Comment by L3Z4** [comment]
I add a property on the `FtpClient` to add the `ConnectionType`. The "set" is protected so the "proxified" implementation can declare when constructed.
I can not bring myself to create an enum to define the ProxyType ; it is too limiting.
I won't merge the proxies, they have segregated responsibilities and implementations.
The factory method in the FtpClient class didn't make sense neither.

I hope the code is acceptable as is. If not, I will let you modify it as you please.

**Comment by springcomp** [comment]
@hgupta9 

I'm working with @LZ34 on this feature. Please, let me explain a bit more about the context of this pull request. We really love FluentFTP and would like to use it in our product, in replacement to the library we currently use. However, we need the FtpClient to support connecting through a proxy.

Many different kinds of proxy exist.

The most common one is an HTTP Proxy. However, there are many more customized protocols out there. For instance, if you check the FTP Proxy Settings dialog of FileZilla, you will find many different options.

FTP Proxy Settings

For one of our client, we needed to support the USER@HOST form of interaction with a proxy.

We figured there were two approaches to modify your library so that a proxy can be supported. One way to do that is to include support for the two supported proxies in your library. In that case, your suggestion to use a enumeration `ConnectionType` or `ProxyType` makes sense. However, this would hardcode the list of supported proxies. If one would like to add a third kind of interaction with a proxy, one would need to further modify the library.

The change that we are trying to make for this pull request is rather to make your library extensible with regards to which kind of proxy to use. Making the type of proxy a kind of _plugin_ if you like. That's why we are recommending using different concrete implementations of a simple base class and that's why there are two implementation in our pull request.

Getting back to the three suggestions, none of them allow us to make an extensible design. We would really love to be able to plug different proxy classes without modifying the library in the future. In this pull request, you have two different implementations, for two different forms of interaction with a proxy.

Perhaps, because an HTTP proxy is so common we could have it built in the library. And if you prefer, bring the less common USER@HOST form of interaction in a separate library. In that case, the library would be modified to make it extensible and support third-party plugins. We could make a simple interop library that defines the base class for third-party plugins. And bring an additional library for the USER@HOST proxy.

Please, let us know how we can help you move forward with this change.

You talked about ways to test this pull request. In our product, we have written a dummy proxy server that can be used to exercise the code. So that would be an addition to this project as well.

**Comment by hgupta9** [comment]
Thanks for the detailed rationale. In response to your points:

> "If one would like to add a third kind of interaction with a proxy, one would need to further modify the library."

I don't understand why people simply couldn't take the source, add their changes and re-build the library. Its not closed source.

> Getting back to the three suggestions you made, none of them allow us to make an extensible design. We would really love to be able to plug different proxy classes without modifying the library in the future. In this pull request, you have two different implementations, for two different forms of interaction with a proxy.

Again, I don't understand but I accept. I'll merge this PR and think about refactoring later. 

Can the naming be improved? For example `FtpProxy` instead of `FtpClientProxy`? What do you suggest?

**Comment by springcomp** [comment]
> I don't understand why people simply couldn't take the source, add their changes and re-build the library. Its not closed source.

I think that's the heart of the discussion. Yes, people can definitely modify the library themselves. After all, that's what we have currently done to help us move forward. However, our modifications are not part of the "standard" and official library. Therefore, we have the code for our modifications in one of our repo and we will need to maintain it.

We would much rather have the standard library merge our changes in the best possible way and modify our code to discard our modifications and use the next version of the library with the new features.

In making this pull request, it is not our intent to waste your time. I will happily change the naming to `FtpProxy` and push an updated pull request if you will. Please, let me know what you would plan to refactor and I will happily try and make the changes accordingly to make it easier for you to merge the pull request at a later time.

Does that work for you?

**Comment by hgupta9** [comment]
I've merged the PR and cleaned it up in this [commit](https://github.com/hgupta9/FluentFTP/commit/30d22cb126b4c3eabedadccb38f96170c5fb726c). Can you test and see if it works fine for you?

**Comment by hgupta9** [comment]
@springcomp and @L3Z4 - Thanks for your contribution. I appreciate your efforts in adding FTP proxy support to FluentFTP.

**Pull request merged**
