### PR TITLE
Fixed FtpTrace Bug & Fixed Ordering in Uploads

### PR DESCRIPTION
**Pull request by jblacker**
- Fixed FtpTrace bug
- Updated Documentation about FtpTrace & FtpVerify
- Fixed ordering of events in upload to improve reliability upon a verification failure

### CODE REVIEW

**Comment by hgupta9** [comment]
Thanks again.

**Comment by jblacker** [comment]
@hgupta9  Of course dude.  Happy to contribute!

**Comment by hgupta9** [comment]
I pushed all changes to nuget. Lets hope all is well - https://www.nuget.org/packages/FluentFTP/17.3.0

And can you help me by showing the correct code for this [FAQ entry](https://github.com/hgupta9/FluentFTP#faq_logfile)?

**Comment by hgupta9** [comment]
Oh forget it. Just saw the new section you added to the readme. Thanks!

**Pull request merged**
