### PR TITLE
Added external ip resolver

### PR DESCRIPTION
**Pull request by worstenbrood**

### CODE REVIEW

**Comment by hgupta9** [comment]
Can you rename the method `IpifyResolve()` to `GetPublicIP()` or `GetInternetIP()`

Also, in all of the comments please use "IP" instead of "ip"

**Comment by worstenbrood** [comment]
Done :-)

**Comment by hgupta9** [comment]
Thank you for the great work! Really appreciated...

**Comment by worstenbrood** [comment]
Np, both the active ports range and the ip resolver made the library usable for a project :-)

**Pull request merged**
